### ISSUE TITLE
IAC assumes the use of virtual machines

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/infrastructure#1]
Hi, I think there is a fundamental problem here. 

Osmosis really doesn't work in iac envionments.  That whole mantra is about using cloud apis and the like but the majority of clouds do not have the capability to run osmosis properly.

**Comment by faddat** [comment]
Hey, if the virtual machines were on-prem, then could use fast disks.  For a single-node testnet though it isn't so hard, and it may be preferable to just script that out in github actions.  All will depend on the type of testnet one wants to achieve.

**Comment by daniel-farina** [comment]
@faddat 
I agree with you, for a node it will most likely get recycled but we could look into creating a Tendermint module for Terraform long term. 

Right now we are exploring the option of setting up testnet for dev environments. Doing simple things such as automatically adding several of ssh keys to a node when developers are working together and quickly recycling exact replicas of it is the goal of this effort. 

The other part we would like to explore is the actual IAC of the entire stack, from DNS entries to services that are used to maintain the applications and APIs that are available, right now we have some blackboxes that can be documented via IAC.

Thank you for  looking into this!  I'll keep you posted!
